FROM mcr.microsoft.com/mssql/server:latest
RUN echo **** SQL Server-Repo ****

ENV TZ=Asia/Singapore
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV portnum=1433
ENV endpt_server=0.0.0.0
EXPOSE $portnum
# ENTRYPOINT ["mlflow", "server"]
CMD mlflow server -p $portnum --host $endpt_server
